# Generated by Django 3.2.9 on 2022-01-25 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Go_messege',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Subject', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('State', models.CharField(default='', max_length=30)),
                ('City', models.CharField(default='', max_length=30)),
                ('Messege', models.CharField(default='', max_length=1000)),
            ],
            options={
                'db_table': 'go_messege',
            },
        ),
        migrations.CreateModel(
            name='Master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Email', models.EmailField(max_length=50, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField(default=False)),
                ('DateCreated', models.DateTimeField(auto_now_add=True)),
                ('DateUpdated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'Master',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Role', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Select_Category', models.CharField(default='', max_length=20)),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Subject', models.CharField(default='', max_length=15)),
                ('Address', models.CharField(default='', max_length=200)),
                ('PoliceStation', models.CharField(default='', max_length=20)),
                ('Mobile', models.CharField(default='', max_length=12)),
                ('Discription', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'report',
            },
        ),
        migrations.CreateModel(
            name='Police_Varification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('FatherName', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('City', models.CharField(default='', max_length=20)),
                ('PoliceStation', models.CharField(default='', max_length=20)),
                ('Pin_Code', models.CharField(default='', max_length=12)),
                ('House_No', models.CharField(default='', max_length=10)),
                ('Dicripstion', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'police_varification',
            },
        ),
        migrations.CreateModel(
            name='Passport_Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dob', models.DateField(auto_created=True, null=True)),
                ('FullName', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=200)),
                ('Select_Appliction_Type', models.CharField(default='', max_length=20)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'passport_status',
            },
        ),
        migrations.AddField(
            model_name='master',
            name='Role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.role'),
        ),
        migrations.CreateModel(
            name='Lost_Parson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(auto_created=True, null=True)),
                ('FullName', models.CharField(default='', max_length=20)),
                ('FatherName', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('State', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('PoliceStation', models.CharField(default='', max_length=20)),
                ('Identification_Mark', models.CharField(default='', max_length=10)),
                ('Identity_Card', models.CharField(default='', max_length=10)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Discription', models.CharField(default='', max_length=500)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'lost_parson',
            },
        ),
        migrations.CreateModel(
            name='E_fir',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('CriminalName', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('State', models.CharField(default='', max_length=20)),
                ('City', models.CharField(default='', max_length=20)),
                ('PoliceStation', models.CharField(default='', max_length=20)),
                ('Pin_Code', models.CharField(default='', max_length=10)),
                ('House_No', models.CharField(default='', max_length=10)),
                ('E_fir', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'e_fir',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='default.png', upload_to='department/profile_img/')),
                ('FullName', models.CharField(default='', max_length=30)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('West Bangal', 'West bangal'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Panjab', 'Panjab')], max_length=20)),
                ('City', models.CharField(choices=[('Patna', 'Patna'), ('Chhapra', 'Chhapra'), ('Hagipur', 'Hagipur'), ('Siwan', 'Siwan'), ('Mairwa', 'Mairwa'), ('Aara', 'Aara'), ('Gopalganj', 'Gopalganj')], max_length=20)),
                ('Pin_Code', models.CharField(default='', max_length=10)),
                ('House_No', models.CharField(default='', max_length=10)),
                ('Discription', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'department',
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(blank=True, default='', max_length=20)),
                ('FatherName', models.CharField(default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('West Bangal', 'West bangal'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Panjab', 'Panjab')], max_length=20)),
                ('City', models.CharField(choices=[('Patna', 'Patna'), ('Chhapra', 'Chhapra'), ('Hagipur', 'Hagipur'), ('Siwan', 'Siwan'), ('Mairwa', 'Mairwa'), ('Aara', 'Aara'), ('Gopalganj', 'Gopalganj')], max_length=20)),
                ('PoliceStation', models.CharField(choices=[('Ganghimadan', 'Ganghimadan'), ('Danapur', 'Danapur'), ('Gayghat', 'Gayghat'), ('Baudha calony', 'Baudha calony'), ('Boring Road', 'Boring road'), ('Bally Road', 'Bally road'), ('Kankadbag', 'Kankadbag')], max_length=20)),
                ('Pin_Code', models.CharField(default='', max_length=10)),
                ('House_No', models.CharField(default='', max_length=10)),
                ('Discription', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
        ),
        migrations.CreateModel(
            name='Citizen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.FileField(default='default.png', upload_to='citizen/profile_img/')),
                ('FullName', models.CharField(blank=True, default='', max_length=20)),
                ('Address', models.CharField(default='', max_length=200)),
                ('Country', models.CharField(default='', max_length=20)),
                ('State', models.CharField(choices=[('Bihar', 'Bihar'), ('Jharkhand', 'Jharkhand'), ('Odisha', 'Odisha'), ('West Bangal', 'West bangal'), ('Gujrat', 'Gujrat'), ('Haryana', 'Haryana'), ('Panjab', 'Panjab')], max_length=20)),
                ('City', models.CharField(choices=[('Patna', 'Patna'), ('Chhapra', 'Chhapra'), ('Hagipur', 'Hagipur'), ('Siwan', 'Siwan'), ('Mairwa', 'Mairwa'), ('Aara', 'Aara'), ('Gopalganj', 'Gopalganj')], max_length=20)),
                ('Pin_Code', models.CharField(default='', max_length=10)),
                ('House_No', models.CharField(default='', max_length=10)),
                ('Discription', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.complaint')),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
        migrations.CreateModel(
            name='Accident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FullName', models.CharField(default='', max_length=20)),
                ('Adhar_No', models.CharField(default='', max_length=12)),
                ('Address', models.CharField(default='', max_length=200)),
                ('City', models.CharField(default='', max_length=20)),
                ('PoliceStation', models.CharField(default='', max_length=20)),
                ('Age', models.CharField(default='', max_length=12)),
                ('Car_No', models.CharField(default='', max_length=10)),
                ('Accident_Car', models.CharField(default='', max_length=10)),
                ('Discription', models.CharField(default='', max_length=1000)),
                ('Gender', models.CharField(choices=[('m', 'Male'), ('f', 'Female')], max_length=15)),
                ('Master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='policeStation_app.master')),
            ],
            options={
                'db_table': 'accident',
            },
        ),
    ]
