# Generated by Django 3.1.7 on 2022-02-18 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('policeStation_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='e_fir',
            name='Pin_Code',
        ),
        migrations.RemoveField(
            model_name='police_varification',
            name='Dicripstion',
        ),
        migrations.RemoveField(
            model_name='report',
            name='Gender',
        ),
        migrations.AddField(
            model_name='police_varification',
            name='Discription',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='passport_status',
            name='Select_Appliction_Type',
            field=models.CharField(choices=[('RTI', 'RTI'), (' Passport|PCC|IC|GEP', 'Passport|PCC|IC|GEP'), ('Diplomite|Offical|Application', 'Diplomite|Offical|Application'), ('Appeal Application', 'Appeal Application ')], max_length=30),
        ),
    ]
