# Generated by Django 3.1.7 on 2022-02-20 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policeStation_app', '0002_auto_20220218_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='citizen',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='department',
            name='Image',
        ),
    ]
